---
# tasks file for cache
- name: copy Cache templates
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     mode: "{{ item.mode }}"
  loop:
     - { src: "templates/cacheinstall", dest: "/tmp/cacheinstall", mode: "0744" }
     - { src: "templates/cache.service", dest: "/usr/lib/systemd/system/cache.service", mode: "0444" }
- name: Copy Cache iso
  copy:
     src: files/Cache2012.iso
     dest: /var/opt/Cache2012.iso
     owner: root
     group: root
     mode: 0444
- name: Creates cache install directory
  file:
    path: /mnt/cache
    state: directory
- name: Mount the iso
  command: "mount /var/opt/Cache2012.iso /mnt/cache"
- name: "Change shared memory settings"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: 'kernel.shmall', value: '2097152' }
    - { name: 'kernel.shmmax', value: '333554432' }
- name: "Run the Cache install script"
  command "/tmp/cacheinstall {{ platform }}"
- name: Copy the Cache key file
  copy:
     src: "{{ key_loc }}"
     dest: "{{ inst_dir }}/mgr/cache.key"
  when: 
   - key_bool=="Y" 

 

