---
# handlers file for cache
- name: Reload the systemd service daemon
  command: "systemctl daemon-reload"
- name: restart cache
  service:
     name: cache
     state: restarted
     enabled: "yes"
